Classes

(10 points )Write a program by creating an 'Employee' class having the following functions and print the final salary.

1 - 'getInfo()' which takes the salary, number of hours of work per day of employee as parameters

2 - 'AddSal()' which adds 10 to the salary of the employee if it is less than $500.

3 - 'AddWork()' which adds 5 to the salary of the employee if the number of hours of work per day is more than 6 hours.

(5 points) Add a method to the previous  class that would print the information (name, year of joining, salary, address). The output Name        Year of joining        Address

Robert        1994        64C- WallsStreat

(5 points )Write a Shape class that has an empty initializer and a empty method for Area

(5 points ) Write a program to extend the Shape class for the previous problem by creating a class named 'Triangle' with an overridden function to print and calculate the area and add a function o print and calculate perimeter. This Triangle class should take in the length of each of its two sides, and the angle between them when initialized. ** Area = (ab × sin C)/2

import math

# Return the sine of different values
print (math.sin(0.00))

(5 points ) Write a program to extend the Shape class for the previous problem by creating a class named Rectangle with an overridden function to print and calculate the area and add a function to print and calculate perimeter. This Rectangle class should take in the height and width when initialized. ** Area = (height * width)

In [35]:
class Employee: # create an employee class
    def __init__(self, name, joining_year, home_address): # takes name, joining year and home address
        self.name = name # initialise name
        self.joining_year = joining_year # initialise joining year
        self.home_address = home_address # initialise adress
        self.wage = 0 # initialise wage
        self.hours = 0 # initialise hours

    def getInfo(self, wage, hours_worked): # get info method
        self.wage = wage
        self.hours = hours_worked

    def AddSal(self): # add sal method
        if self.wage < 500: self.wage += 10

    def AddWork(self): # add work method
        if self.hours > 6: self.wage += 5

    def print(self): # method for printing
        print('{:<20}{:>10}{:>15}{:^40}'.format('Name', 'Joining Year', 'Salary', 'Home Address'))
        print(f'{self.name:<20}{self.joining_year:>10}{self.wage:>15}{self.home_address:^40}')

emp = Employee('Robert',1994,'64C Walls Street')
emp.getInfo(400,7)
emp.AddSal()
emp.AddWork()
emp.print()

Name                     Joining Year         Salary              Home Address              
Robert                    1994            415            64C Walls Street            


In [46]:
import math # import math library 
class Shape: # create shape class
    def __init__(self): # initialise 
        pass
    def Area(self): # create area method
        pass

class Triangle(Shape): # add to shape class because all triangles are shapes 
    def __init__(self, sideA , sideB, angle): # initialise class 
        self.sideA = sideA # initialise side A and B
        self.sideB = sideB
        self.angle = angle # initialise the angle for sine part
    def Area(self): # create area method
        return self.sideA*self.sideB*math.sin(math.radians(self.angle))/2 # function to get the area of the triangle with sides of length sideA and sideB and angle of angle
class Rectangle(Shape): # add to shape class because all rectangles are shapes
    def __init__(self,h, w):  # initialise 
        self.h = h # height
        self.w = w # weight
    def Area(self):
        return self.h*self.w # formula for area of rectangle 

t = Triangle(3,4,73)
print('Triangle Area:',t.Area())
r = Rectangle(5,6)
print('Rectangle Area:', r.Area())

Triangle Area: 5.737828535778212
Rectangle Area: 30


NumPy

NumPy

Show work using python for each problem

(20 points)Write a program by creating an ‘BigMatrixMath’ class having the following functions perform and add in large NumPy arrays .

1 - Initialization creates and empty list 

2 - addMatrix() takes in a NumPy array of unknown size and appends it to the list, if no array is given this should default to add in a NumPy array of size 40 x 40  with all integers between the values of [-70, 159]

3 - printDimension goes and prints the dimensions of every NumPy array in the list

4 – dotProductElgible takes in two array indices and checks if the dot product can be performed on them based on there dimensions

(5 points) create an array with values that are spaced linearly in a specified interval between 0.0 100.0 as a numpy.float64, over 25 values

(5 points) given the following arrays show me a line where I can combine the values into a larger array:

a = np.array([[56, 12], [39, 74]])

b = np.array([[65, 76]])

 expected output

array([

         [ 56, 12],

         [ 39, 74],

         [ 65, 76]

]);

(5 points) Whats a command to reformat a singular dimension array of 12 elements into a 3, 4 matrix.

In [50]:
import numpy as np # import numpy library
class BigMatrixMath: # create big matrix class
        def __init__(self): # initialise and create empty list for matrix
                self.matrix = []
        def addMatrix(self, array = np.random.randint(-70,159,(40,40))): # method to get 40 x 40 matrix with random ints between -70 and 159
                self.mat.append(array) 
        def printDimension(self): # method for printing the matrix
                for array in self.mat:
                        print(array.shape)
        def dotProductElgible(self, i, j): # method for dot product eligibility
                dimension1 = (self.matrix)[i].shape
                dimension2 = (self.matrix)[j].shape
                if(dimension1[1] == dimension2[0]): 
                  return True # can be dot producted
                else: 
                  return False # can't be dot producted

array = np.linspace(0.0,100.0,25, dtype = np.float64)
print(array) # print array

a = np.array([[56,12],[39,74]]) # matrix a
b = np.array([[65,76]]) # matrix b
appended_array = np.append(a,b,0) # appending
print(appended_array) # print appended matrix

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12]) # take on an array
print(array) # print 1x12 array
np.reshape(array,(3,4)) # rearrange array
print(np.reshape(array,(3,4))) # print the rearranged array

[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]
[[56 12]
 [39 74]
 [65 76]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Pandas

(5 points) adult.csv what is the average age of adults that make under 50K? whats the average age of adults that make over 50K.

(5 points) adult.csv what is the standard deviation of hours worked of adults that make under 50K? whats the average age of adults that make over 50K.

(5 points) adult.csv what is the correlation between of hours worked and age of adults that make under 50K? whats the average age of adults that make over 50K.

(5 points) cars.csv replace each text value for a meaningful integer equivalent for each column in  the data.

(5 points) cars.csv what’s the correlation between buying, safety, and maintence.

(5 points) iris.csv what is the median petal length and width for each flower type

(5 points) iris.csv what is the correlation for each flower type

In [17]:
# import the csvs
from google.colab import files
uploaded = files.upload()
uploaded

KeyboardInterrupt: ignored

In [61]:
import pandas as pd # import pandas and numpy library
import numpy as np
df_adult = pd.read_csv(r'adult.csv') # assign df_adult to the adult csv
#print(df_adult)
under_fifty = df_adult[df_adult['class'] ==" <=50K"]
# print(under_fifty) # table of all adults who earn 50k or less
print("Average age of adults earning under 50K:",under_fifty['age'].mean()) # take mean of age column in under_fifty
print("St.Dev of hours worked of adults that make undeer 50K:",under_fifty['hours-per-week'].std()) # take st dev of hours worked column in under_fifty
over_fifty = df_adult[df_adult['class'] != " <=50K"] # table with all adults who earn over 50
# print(over_fifty)
print("Average age of adults earning over 50K", over_fifty['age'].mean()) # mean of age column in over_fifty
column_1 = under_fifty['hours-per-week'] # define column_1
column_2 = under_fifty['age'] # define column_2
correlation = column_1.corr(column_2) # get correlation between hours per week and age 
print("The correlation between hours worked and age of adults that earn under 50K is:",correlation)

Average age of adults earning under 50K: 36.90160398975603
St.Dev of hours worked of adults that make undeer 50K: 12.327423480966102
Average age of adults earning over 50K 44.35659574468085
The correlation between hours worked and age of adults that earn under 50K is: 0.030756630653757777


In [52]:
df_car = pd.read_csv(r'car.csv') # define df_car from car csv
#df_car
df_car['Buying'] = df_car['Buying'].replace(["vhigh"],100000) # replace vhigh
df_car['Buying']
#df_car
df_car['Buying'] = df_car['Buying'].replace(["med"],50000) # replace med
df_car['Buying']
#df_car
df_car['Buying'] = df_car['Buying'].replace(["high"],80000) # replace high
df_car['Buying']
#df_car
df_car['Buying'] = df_car['Buying'].replace(["low"],20000) # replace low
df_car['Buying']
#df_car
df_car['Buying'] = df_car['Buying'].replace(["vlow"],5000) # replace vlow
df_car['Buying']
#df_car
df_car['Maintenance'] = df_car['Maintenance'].replace(["low"],100) # replace low
df_car['Maintenance']
#df_car
df_car['Maintenance'] = df_car['Maintenance'].replace(["med"],500) # replace med
df_car['Maintenance']
#df_car
df_car['Maintenance'] = df_car['Maintenance'].replace(["high"],1000) # replace high
df_car['Maintenance']
#df_car
df_car['Maintenance'] = df_car['Maintenance'].replace(["vhigh"],2000) # replace vhigh
df_car['Maintenance']
#df_car
df_car['Doors'] = df_car['Doors'].replace(["5more"],5) # replace 5more
df_car['Doors']
#df_car
df_car['Riders'] = df_car['Riders'].replace(["more"],5) # replace more
df_car['Riders']
#df_car
df_car['Trunk_Size'] = df_car['Trunk_Size'].replace(["small"],1) # replace small
df_car['Trunk_Size']
#df_car
df_car['Trunk_Size'] = df_car['Trunk_Size'].replace(["med"],2) # replace med
df_car['Trunk_Size']
#df_car
df_car['Trunk_Size'] = df_car['Trunk_Size'].replace(["big"],3) # replace big
df_car['Trunk_Size']
#df_car
df_car['Safety'] = df_car['Safety'].replace(["low"],1) # replace low
df_car['Safety']
#df_car
df_car['Safety'] = df_car['Safety'].replace(["med"],2) # replace med
df_car['Safety']
#df_car
df_car['Safety'] = df_car['Safety'].replace(["high"],3) # replace high
df_car['Safety']
#df_car
df_car['Class'] = df_car['Class'].replace(["unacc"],0) # replace unacceptable
df_car['Class']
#df_car
df_car['Class'] = df_car['Class'].replace(["acc"],1) #  replace acceptable
df_car['Class']
#df_car
df_car['Class'] = df_car['Class'].replace(["good"],2) #  replace good
df_car['Class']
#df_car
df_car['Class'] = df_car['Class'].replace(["vgood"],3)  # replace vgood
df_car['Class']
#df_car
print(df_car) # print the updated data frame
columns_corr = df_car[['Buying','Safety','Maintenance']].corr() # create correlation between 3 columns
print("The correlation matrix is: \n",columns_corr)


      Buying  Maintenance Doors Riders  Trunk_Size  Safety  Class
0     100000         2000     2      2           1       1      0
1     100000         2000     2      2           1       2      0
2     100000         2000     2      2           1       3      0
3     100000         2000     2      2           2       1      0
4     100000         2000     2      2           2       2      0
...      ...          ...   ...    ...         ...     ...    ...
1723   20000          100     5      5           2       2      2
1724   20000          100     5      5           2       3      3
1725   20000          100     5      5           3       1      0
1726   20000          100     5      5           3       2      2
1727   20000          100     5      5           3       3      3

[1728 rows x 7 columns]
The correlation matrix is: 
                    Buying        Safety   Maintenance
Buying       1.000000e+00 -1.557585e-15 -4.784096e-16
Safety      -1.557585e-15  1.000000e+00 -2.347

In [53]:
df_iris = pd.read_csv(r'iris.csv') # define iris from iris csv
df_iris
df_iris['Flower_class'].unique() # get unique classes
# 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica' # these are unique classes
df_irisSETOSA = df_iris[df_iris['Flower_class']=='Iris-setosa'] # new df
#print(df_irisSETOSA)
df_irisVERSICOLOR = df_iris[df_iris['Flower_class']=='Iris-versicolor'] # new df
#print(df_irisVERSICOLOR)
df_irisVIRGINICA = df_iris[df_iris['Flower_class']=='Iris-virginica'] # new df
#print(df_irisVIRGINICA)
med_pet_length_setosa = df_irisSETOSA['Petal_length'].median() # median petal length from setosa df
print("Medium SETOSA petal length:",med_pet_length_setosa)
med_pet_length_versicolor = df_irisVERSICOLOR['Petal_length'].median() # median petal length from versicolor df
print("Medium SETOSA petal length:",med_pet_length_versicolor)
med_pet_length_virginica = df_irisVIRGINICA['Petal_length'].median() # median petal length from virginica df
print("Medium SETOSA petal length:",med_pet_length_virginica)
med_pet_width_setosa = df_irisSETOSA['Petal_width'].median()  # median petal width from setosa df
print("Medium SETOSA petal width:",med_pet_width_setosa)
med_pet_width_versicolor = df_irisVERSICOLOR['Petal_width'].median() # median petal width from versicolor df
print("Medium SETOSA petal width:",med_pet_width_versicolor)
med_pet_width_virginica = df_irisVIRGINICA['Petal_width'].median() # median petal width from virginica df
print("Medium SETOSA petal width:",med_pet_width_virginica)
#corr1 = df_irisSETOSA.corrwith(df_irisVERSICOLOR, axis = 1)
#print("The correlation between Setosa and Versicolor is:", corr1)
#corr2= df_irisSETOSA.corrwith(df_irisVIRGINICA, axis = 1)
#print("The correlation between Setosa and Virginica is:", corr2)
#corr3 = df_irisVERSICOLOR.corrwith(df_irisVIRGINICA, axis = 1)
#print("The correlation between Versicolor and Virginica is:", corr3#)
# im not sure why, but i keep getting NaNs for this part :(

Medium SETOSA petal length: 1.5
Medium SETOSA petal length: 4.35
Medium SETOSA petal length: 5.55
Medium SETOSA petal width: 0.2
Medium SETOSA petal width: 1.3
Medium SETOSA petal width: 2.0
The correlation between Setosa and Versicolor is: 0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
      ..
95   NaN
96   NaN
97   NaN
98   NaN
99   NaN
Length: 100, dtype: float64
